Added reservation action
dotnetdew/Parking-Zone3 pull request #13
Opened 2024-02-04 16:35 UTC by dotnetdew

2024-02-05 10:21 UTC, DilshodMQ requested changes

2024-02-05 10:21 UTC, DilshodMQ commented on Parking-Zone/Areas/User/Controllers/ReservationController.cs
> +                {
should be added model error if Slot is not free and show this error in the view

2024-02-05 10:21 UTC, DilshodMQ commented on Parking-Zone/Areas/User/Controllers/ReservationController.cs
> +                    _reservationService.Insert(reservation);
Who has create this Reservation?  Add FK to AppUser from Reservation Model and attach the current User

2024-02-05 10:21 UTC, DilshodMQ commented on Parking-Zone/Areas/User/Views/Reservation/Reserve.cshtml
> +            <input type="hidden" value="@Model.SlotNumber" asp-for="SlotNumber" />
Why you need the last three input? only slotID is enaugh

2024-02-05 10:21 UTC, DilshodMQ commented on Parking-Zone/Areas/User/Controllers/ReservationController.cs
> +
what if slot ==null (also test for this case)

2024-02-05 10:21 UTC, DilshodMQ commented on Tests/Controllers/ReservationControllerTests.cs
> +            var result = controller.Reserve(_testSlotId, testStartTime, 2);
create var for duration and use it

2024-02-06 16:32 UTC, napster1991 requested changes

2024-02-06 16:32 UTC, napster1991 commented on Parking-Zone/ViewModels/Reservation/ReserveVM.cs
> +        public Guid SlotId { get; set; }
Also required

2024-02-06 16:32 UTC, napster1991 commented on Parking-Zone/Areas/User/Controllers/ReservationController.cs
> +                reservation.AppUserId = _userManager.GetUserId(User);
Fetch userId from context Identity. Then you can remove userManager from controller.

2024-02-06 16:32 UTC, napster1991 commented on Parking-Zone/Areas/User/Views/Reservation/Reserve.cshtml
> +            <input type="hidden" value="@Model.SlotId" asp-for="SlotId" />
I guess, no need in setting the default value.

2024-02-06 16:32 UTC, napster1991 commented on Tests/Controllers/ReservationControllerTests.cs
> +
Please, add regions.

2024-02-06 16:32 UTC, napster1991 commented on Tests/Controllers/ReservationControllerTests.cs
> +
Add test case, about which Dilshod mentioned

2024-02-06 16:32 UTC, napster1991 commented on Tests/Controllers/ReservationControllerTests.cs
> +        }
Add test case when slot is not free

2024-02-07 04:02 UTC, napster1991 requested changes

2024-02-07 04:02 UTC, napster1991 commented on Parking-Zone/Areas/User/Controllers/ReservationController.cs
> +                return View(reserveVM);
No need in this return.

2024-02-07 04:07 UTC, napster1991 requested changes

2024-02-07 04:07 UTC, napster1991 commented on Parking-Zone/Services/ReservationService.cs
> +            entity.Id = Guid.NewGuid();
Move this line to base Service class (do the same for other inherited services as well).

2024-02-07 10:24 UTC, napster1991 commented on Parking-Zone/Areas/User/Controllers/ReservationController.cs
> +
Remove unnecessary empty lines

2024-02-07 10:28 UTC, napster1991 approved these changes

2024-02-07 10:41 UTC, merged