Slot category cannot be changed if its in use
dotnetdew/Parking-Zone3 pull request #19
Opened 2024-02-16 06:52 UTC by dotnetdew

2024-02-16 10:39 UTC, DilshodMQ requested changes

2024-02-16 10:39 UTC, DilshodMQ commented on Parking-Zone/ViewModels/ParkingSlot/ParkingSlotEditVM.cs
> +            this.HasAnyActiveReservation = slot.Reservations.Any(slot => slot.IsActive == true);
not slot, reservation in lambda expression

2024-02-16 10:39 UTC, DilshodMQ commented on Parking-Zone/Areas/Admin/Controllers/ParkingSlotController.cs
> +                    ModelState.AddModelError("Category", "Category cannot be changed it is in use");
you should check ModelState after adding ModelError

2024-02-16 12:16 UTC, napster1991 requested changes

2024-02-16 12:16 UTC, napster1991 commented on Parking-Zone/ViewModels/ParkingSlot/ParkingSlotEditVM.cs
> +            this.HasAnyActiveReservation = slot.Reservations.Any(r => r.IsActive == true);
```suggestion
            this.HasAnyActiveReservation = slot.Reservations.Any(r => r.IsActive);
```

2024-02-16 12:16 UTC, napster1991 commented on Parking-Zone/ViewModels/ParkingSlot/ParkingSlotEditVM.cs
> +        public bool HasAnyActiveReservation { get; set; } = false;
```suggestion
        public bool HasAnyActiveReservation { get; set; };
```
Boolean property is false by default.

2024-02-16 12:16 UTC, napster1991 commented on Parking-Zone/Areas/Admin/Views/ParkingSlot/Edit.cshtml
> +                @if (Model.HasAnyActiveReservation == true)
```suggestion
                @if (Model.HasAnyActiveReservation)
```

2024-02-16 12:16 UTC, napster1991 commented on Parking-Zone/Areas/Admin/Controllers/ParkingSlotController.cs
> +                return View(parkingSlotEditVM);
Remove this line.

2024-02-16 12:16 UTC, napster1991 commented on Parking-Zone/Areas/Admin/Controllers/ParkingSlotController.cs
> +            if (parkingSlotEditVM.HasAnyActiveReservation == true && existingSlot.Category != parkingSlotEditVM.Category)
1. You cannot rely on property coming from view.
2. HasAnyActiveReservation is not used on view.

2024-02-16 12:16 UTC, napster1991 commented on Tests/Controllers/ParkingSlotControllerTests.cs
> +            }
Please, explain, how these lines help to test new code.

2024-02-17 09:30 UTC, DilshodMQ requested changes

2024-02-17 09:30 UTC, DilshodMQ commented on Parking-Zone/ViewModels/ParkingSlot/ParkingSlotEditVM.cs
> +            this.HasAnyActiveReservation = slot.Reservations.Any(r => r.IsActive);
Get this property from slot

2024-02-17 09:30 UTC, DilshodMQ commented on Tests/Controllers/ParkingSlotControllerTests.cs
> +                new Reservation()
use new() this  instead new Reservation()

2024-02-18 11:10 UTC, napster1991 approved these changes

2024-02-18 11:10 UTC, napster1991 commented on Parking-Zone/Areas/Admin/Controllers/ParkingSlotController.cs
> +            if (existingSlot.HasAnyActiveReservation == true && existingSlot.Category != parkingSlotEditVM.Category)
```suggestion
            if (existingSlot.HasAnyActiveReservation && existingSlot.Category != parkingSlotEditVM.Category)
```

2024-02-18 11:18 UTC, merged