parking zones dispayed as cards
dotnetdew/Parking-Zone3 pull request #23
Opened 2024-02-20 09:49 UTC by dotnetdew

2024-02-20 13:05 UTC, DilshodMQ requested changes

2024-02-20 13:05 UTC, DilshodMQ commented on Parking-Zone/ViewModels/ParkingZone/ParkingZoneListItemVM.cs
> +            SlotsInUse = zone.ParkingSlots.Count(s => s.HasAnyActiveReservation);
HasAnyAvtiveReservation does not mean this slot currently in use

2024-02-20 13:05 UTC, DilshodMQ commented on Parking-Zone/ViewModels/ParkingZone/ParkingZoneListItemVM.cs
> +            FreeSlots = zone.ParkingSlots.Count(s => s.IsAvailableForBooking);
IsAvailableForBooking does not mean this slot free

2024-02-21 02:46 UTC, DilshodMQ approved these changes

2024-02-21 09:22 UTC, napster1991 approved these changes

2024-02-21 10:45 UTC, merged