Us026 add filtering for slots index
dotnetdew/Parking-Zone3 pull request #25
Opened 2024-02-23 15:31 UTC by dotnetdew

2024-02-26 10:18 UTC, DilshodMQ requested changes

2024-02-26 10:18 UTC, DilshodMQ commented on Parking-Zone/Areas/Admin/Controllers/ParkingSlotController.cs
> +        public IActionResult LoadData(string category, bool isFree, string zoneId)
Use one object instead of three arguments

2024-02-26 10:18 UTC, DilshodMQ commented on Parking-Zone/Areas/Admin/Controllers/ParkingSlotController.cs
> +                return Json(slots.Select(x => new ParkingSlotListItemVM(x)).ToList());
Where is Filtring by IsFree

2024-02-26 10:18 UTC, DilshodMQ commented on Parking-Zone/Areas/Admin/Controllers/ParkingSlotController.cs
> +                var filteredSlots = slots.Where(s => s.Category == parsedCategory && s.HasAnyActiveReservation == isFree).ToList();
If HasAnyActiveReservation is true, it means this slot is not Free

2024-02-26 10:18 UTC, DilshodMQ commented on Parking-Zone/Areas/Admin/Views/ParkingSlot/Index.cshtml
> +                data: {
Use an object

2024-02-26 10:18 UTC, DilshodMQ commented on Parking-Zone/Areas/Admin/Views/ParkingSlot/Index.cshtml
> +            }
these lines are not necessary. Use jquery to Populate table this code has written below

2024-02-26 10:18 UTC, DilshodMQ commented on Parking-Zone/Areas/Admin/Controllers/ParkingSlotController.cs
> +        }
Move the logic part into Service

2024-02-26 10:18 UTC, DilshodMQ commented on Parking-Zone/Areas/Admin/Views/ParkingSlot/Index.cshtml
> +</style>
Separate the custom CSS another file

2024-02-27 03:22 UTC, DilshodMQ approved these changes

2024-02-27 16:14 UTC, DilshodMQ requested changes

2024-02-27 16:14 UTC, DilshodMQ commented on Parking-Zone/Areas/Admin/Controllers/ParkingSlotController.cs
> +                return BadRequest("Slot Not Found");
Zone

2024-02-27 16:14 UTC, DilshodMQ commented on Parking-Zone/Services/ParkingSlotService.cs
> +        }
this method will not work correctly in some cases, for example when category != 0  va onlyFree = false

2024-02-28 10:02 UTC, napster1991 requested changes

2024-02-28 10:02 UTC, napster1991 commented on Parking-Zone/Areas/Admin/Views/ParkingSlot/Index.cshtml
> +            <input class="form-check-input" type="checkbox" id="checkboxID" style="margin-bottom: 10px;" />
```suggestion
            <input class="form-check-input" type="checkbox" id="PleaseGiveProperIdNameHere" style="margin-bottom: 10px;" />
```

2024-02-28 10:02 UTC, napster1991 commented on Parking-Zone/Areas/Admin/Views/ParkingSlot/Index.cshtml
> +        var slot = {
Please, pay attention to namings.
For example:

```suggestion
        var slotFilterQueryPayload = {
```

2024-02-28 10:02 UTC, napster1991 commented on Tests/Services/ParkingSlotServiceTests.cs
> +            };
I don't see the difference between this Arrange block and the one in the test above.

2024-02-28 14:08 UTC, napster1991 approved these changes

2024-02-28 14:08 UTC, napster1991 commented on Parking-Zone/Services/Models/FilterSlotsQuery.cs
Remove using on line 2.

2024-02-28 14:58 UTC, merged