Get All Current cars belonging to a Parking Zone
dotnetdew/Parking-Zone3 pull request #26
Opened 2024-02-28 16:03 UTC by dotnetdew

2024-02-29 03:58 UTC, DilshodMQ requested changes

2024-02-29 03:58 UTC, DilshodMQ commented on Parking-Zone/Areas/Admin/Controllers/ParkingZoneController.cs
> +            var plateNumbers = zone.ParkingSlots
Move the logic into Service

2024-02-29 08:47 UTC, napster1991 requested changes
Where are tests for ParkingZoneService.GetPlateNumbers() ?

2024-02-29 08:47 UTC, napster1991 commented on Parking-Zone/Areas/Admin/Controllers/ParkingZoneController.cs
> +        public IActionResult GetCurrentCars(Guid zoneId)
```suggestion
        public IActionResult CurrentCars(Guid zoneId)
```

2024-02-29 08:47 UTC, napster1991 commented on Parking-Zone/Services/IParkingZoneService.cs
> +        public List<string> GetPlateNumbers(ParkingZone zone);
```suggestion
        public List<string> GetCurrentCarsPlateNumbersByZone(ParkingZone zone);
```

2024-02-29 18:50 UTC, napster1991 approved these changes

2024-03-01 01:08 UTC, merged

2024-03-09 14:45 UTC, dotnetdew commented
![](https://github.trello.services/images/mini-trello-icon.png) [US027: Get all current cars (plate numbers) in the parking zone. The zone card (on /Zones/Index) must have a “Current cars” link. Add a corresponding page that lists all current cars in the zone.](https://trello.com/c/pA0ItdI9/36-us027-get-all-current-cars-plate-numbers-in-the-parking-zone-the-zone-card-on-zones-index-must-have-a-current-cars-link-add-a-co)