US028: Add Finance Section For Zone Cards
dotnetdew/Parking-Zone3 pull request #28
Opened 2024-03-05 11:51 UTC by dotnetdew

2024-03-06 06:16 UTC, DilshodMQ requested changes

2024-03-06 06:16 UTC, DilshodMQ commented on Parking-Zone/Areas/Admin/Controllers/ReservationsController.cs
> +        public IActionResult Index(string period)
Add this Action into ParkingZoneController

2024-03-06 06:16 UTC, DilshodMQ commented on Parking-Zone/Areas/Admin/Views/ParkingZone/Index.cshtml
> +                    <select id="periodSelect" class="form-select" aria-label="Default select example" style="width: 165px;">
use enum type in this select, and use html helper to get values of enum

2024-03-06 06:16 UTC, DilshodMQ commented on Parking-Zone/Services/ReservationService.cs
> +        public ReservationHoursSummaryVM GetStandardAndBusinessHoursByPeriod(string period)
It is not VM

2024-03-07 04:20 UTC, DilshodMQ requested changes

2024-03-07 04:20 UTC, DilshodMQ commented on Tests/Services/ReservationServiceTests.cs
> +        {
add tests for other cases

2024-03-07 05:46 UTC, DilshodMQ approved these changes

2024-03-09 14:44 UTC, dotnetdew commented
![](https://github.trello.services/images/mini-trello-icon.png) [US028 (3): Modify Zone card: Also display Finance block with ability to filter by period to see number of hours booked for each category. Use jQuery ajax for filtering.](https://trello.com/c/gUxJHusM/37-us028-3-modify-zone-card-also-display-finance-block-with-ability-to-filter-by-period-to-see-number-of-hours-booked-for-each-cate)

2024-03-10 12:13 UTC, napster1991 approved these changes

2024-03-10 12:13 UTC, napster1991 commented on Parking-Zone/Services/ParkingZoneService.cs
> +            //foreach (var reservation in reservationsForPeriod)
Remove comment

2024-03-10 12:36 UTC, merged