Edit functionality added for user
dotnetdew/Parking-Zone3 pull request #8
Opened 2024-01-23 10:38 UTC by dotnetdew

2024-01-24 03:41 UTC, DilshodMQ requested changes

2024-01-24 03:41 UTC, DilshodMQ commented on Parking-Zone/Areas/Identity/Pages/Account/Manage/Index.cshtml.cs
> +            Username = userName;
why do you need this UserName

2024-01-24 03:41 UTC, DilshodMQ commented on Parking-Zone/Areas/Identity/Pages/Account/Manage/Index.cshtml.cs
> +
where is the FullName change code?

2024-01-24 03:41 UTC, DilshodMQ commented on Parking-Zone/Areas/Identity/Pages/Account/Manage/_Layout.cshtml
> +        </div>
we don't need this partial

2024-01-24 03:41 UTC, DilshodMQ commented on Parking-Zone/Areas/Identity/Pages/Account/Manage/_ManageNav.cshtml
> +</ul>
why do you need this page?

2024-01-24 09:57 UTC, napster1991 requested changes

2024-01-24 09:57 UTC, napster1991 commented on Parking-Zone/Areas/Identity/Pages/Account/Register.cshtml.cs
> +
Remove this line

2024-01-24 09:57 UTC, napster1991 commented on Parking-Zone/appsettings.json
> +    "DefaultConnection": "Server=DESKTOP-U8CO9CB;Database=ParkingZone4;Trusted_Connection=True;TrustServerCertificate=True;"
Why are you constantly switching from one db to another?

2024-01-24 18:42 UTC, napster1991 approved these changes

2024-01-25 04:05 UTC, DilshodMQ approved these changes

2024-01-25 13:32 UTC, merged